### PR TITLE
change three dots to ellipsis

### PR DESCRIPTION
**Pull request by majjejjam**
This better follows the [GNOME HIG](https://developer.gnome.org/hig/guidelines/typography.html).

### CODE REVIEW

**Comment by Rafostar** [comment]
If possible I would like to match other major GNOME applications. Can you name a few that also use ellipsis in menus?

As an example I give `gedit` which does three dots, just like we do:

Screenshot from 2022-01-09 11-07-06

**Comment by Rafostar** [comment]
Another example is `totem`. Also just three dots:

Screenshot from 2022-01-09 11-21-57

**Comment by Rafostar** [comment]
Also GNOME Image Viewer:

Screenshot from 2022-01-09 11-24-28

**Comment by majjejjam** [comment]
I considered this too, and am still unsure whether it’s better to follow the HIG or be consistent with other GNOME applications (for this you’d have to find what’s most used).

It’s often quite difficult to see the difference between the three dots (...) and an ellipsis (…) (the latter is often wider, but it depends on the font). Instead of looking at the actual app, I tried finding what symbol they use by going to the source code on Gitlab and searching for ellipses in the po folder. Without looking through everything, I found Disk Usage Analyzer (baobab), Disk Utility, Builder, Document Viewer (evince), Identity, Contacts and Weather use ellipses.

Some of these are inconsistent within the application, where, sometimes, the translated version corrects for this (see [Builder](https://gitlab.gnome.org/GNOME/gnome-builder/-/blob/main/po/sv.po) and [Contacts](https://gitlab.gnome.org/GNOME/gnome-contacts/-/blob/master/po/sv.po) for examples).

I tried to pick applications at random and, besides the applications you mentioned, only found one that uses three dots: Curtail (also Builder and Contacts, being somewhat inconsistent). I’m sure there are more though.

From this it seems a lot of GNOME apps use ellipses. Because the HIG recommends using this symbol instead of three dots, and the situation already is inconsistent, I think it’s better to be on the “correct” side (and set a good example?). I’d be up to submitting merge requests for more applications using three dots to solidify using ellipses even more!

There are other deviations from the typographical guidelines from the HIG, as Weather seems to use dashes instead of minus symbols:
Skärmbild från 2022-01-09 13-28-00

**Comment by majjejjam** [comment]
I realize grep:ing for the minus symbol doesn't show it’s not used in the weather app – it probably gets data from outside the source code, where negative numbers are annotated with a dash. In this case, following HIG would be a bit more complicated, having to search for the symbol and converting it.

**Comment by Rafostar** [comment]
No, its fine. We can go with the ellipsis (and probably also other Unicode recommendations while at it), but right now due to [https://gitlab.freedesktop.org/freedesktop/freedesktop/-/issues/407](https://gitlab.freedesktop.org/freedesktop/freedesktop/-/issues/407) CI is failing, so merging will need to wait till the network problems are resolved.

**Comment by Rafostar** [comment]
@majjejjam 

You forgot to also apply this change to `ui/clapper.ui` where this string in application comes from. Unless you do, the translation files you generated will not work correctly.

**Comment by majjejjam** [comment]
Sorry, it’s fixed now!

Yeah, it’s near impossible! It’s difficult to argue for a change so insignificant, but I don’t know, it just feels right I guess.

**Pull request merged**
