### PR TITLE
First French translation. Not finished yet.

### PR DESCRIPTION
**Pull request by tuxfollower**
May you accept my pull request so that every french user can enjoy it even more :).

### CODE REVIEW

**Comment by Rafostar** [comment]
> May you accept my pull request so that every french user can enjoy it even more :).

Sure. Thanks. The commit message states "Not finished yet.", so this is currently a work in progress, I presume? Lemme know when its done then. No need to rush.

**Comment by tuxfollower** [comment]
@Rafostar Yes, I know, i'm working on it but i have a question about the shorcuts. It's said double tap (right) or (left) [ui/help-overlay.ui:68] for switching items of a playlist but i don't understand how to do this because a double tap just toggle the fullscreen!
Did i just misunderstood the information? Or Is there some shorcuts not implemented yet? Thanks.

**Comment by tuxfollower** [comment]
And i also noticed that in the shorcuts, it's written "Tap" [ui/help-overlay.ui:33] for Reveal OSD. But tapping do nothing (except double tap). For revealing OSD you need to move the cursor. So shouldn't we change "Tap" to "Move the cursor" or somthing like that. I don't know every meaning of english's words but for me it's unsuitable.

**Comment by Rafostar** [comment]
"Tap" is for touchscreens.

> It's said double tap (right) or (left)

On touchscreen devices like linux mobile phones/tablets you can double tap (touch with finger) on either left/right screen side (only when in fullscreen) to change playlist items. Press and hold on screen for a short while to play/pause. So all "tap" and "press" are for touchscreens.

> And what's the purpose of the seeking category in the settings?

To change if you prefer faster but less accurate seeking or the slower but more accurate behavior and how much you want to seek forward/backward every time you press left/right arrow key (e.g: 10 seconds, 2 minutes, or 15%, etc.).

**Comment by tuxfollower** [comment]
Ok, Thank you. I was wondering indeed because some of these mobile shorcuts also worked with touchpads.

**Comment by tuxfollower** [comment]
@Rafostar Hi, i finally understood the whole interface and evrything is translated in French. Now could you merge my request? I noticed that floating mode in for GNOME was not working. Is it still in developpement? Thank you.(finally clapper in french :smiley:)

**Comment by Rafostar** [comment]
> Hi, i finally understood the whole interface and evrything is translated in French.

Thanks!

> I noticed that floating mode in for GNOME was not working. Is it still in developpement? Thank you.

Latest GNOME Shell version removed app access from the function Clapper was taking advantage of to achieve this. You can use https://extensions.gnome.org/extension/4691/pip-on-top/ to get this back working automatically or alternatively press right click on the player while holding "Super" (Windows) key and select always on top option.

**Comment by Rafostar** [comment]
@tuxfollower 

Since you started working on this there was a small change replacing all 3 dots occurrences with ellipsis symbol. Please update so it can be merged on top of current git. Thanks.

**Comment by Rafostar** [comment]
Also if you could make this whole thing into a single commit that adds French translation (without "unfinished yet" comments) that would be great!

**Comment by tuxfollower** [comment]
@Rafostar Maybe i can just give the two files to you so that you can commit yourself. Because unless i remake a whole new git repos i don't know how to undo commits...

**Comment by Rafostar** [comment]
@tuxfollower 

OK. I did the ellipsis correction and uploaded your translation directly to Crowdin. It is now included in https://github.com/Rafostar/clapper/pull/208 and I will merge it tomorrow. Thanks for your work on this.

**Pull request closed without merging**
